name: Build APK with Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK using Docker
        run: |
          docker run --rm -v "$(pwd)":/home/user/app kivy/kivy:master bash -c "cd /home/user/app && buildozer apk debug"
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker
          path: bin/*.apk
